default_stages:
  - pre-commit

default_language_version:
  python: python3.10

# poetry run pre-commit run --all-files
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        exclude: deployment/helm/charts
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args:
          - --line-length=80

  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
        args:
          - --line-length=120
